openrc: Fix init scripts and installation script.

diff --git a/openrc/init.d/dbus b/openrc/init.d/dbus
--- a/openrc/init.d/dbus
+++ b/openrc/init.d/dbus
@@ -1,32 +1,39 @@
 #!/sbin/openrc-run
-# Copyright (c) 2007-2008 Roy Marples <roy@marples.name>
-# Released under the 2-clause BSD license.
+# Copyright 1999-2016 Gentoo Foundation
+# Distributed under the terms of the GNU General Public License, v2 or later
 
-command=/usr/bin/dbus-daemon
-pidfile=/var/run/dbus/dbus.pid
-command_args="${dbusd_args---system}"
 extra_started_commands="reload"
-name="Message Bus Daemon"
 
-depend()
-{
+description="An IPC message bus daemon"
+pidfile="/var/run/dbus/dbus.pid"
+command="/usr/bin/dbus-daemon"
+command_args="--system"
+
+dbus_socket="/var/run/dbus/system_bus_socket"
+
+depend() {
+	need localmount
 	use logger
 	after bootmisc
 }
 
-start_pre()
-{
-	mkdir -p $(dirname $pidfile)
+start_pre() {
+        rm -f /var/lib/dbus/machine-id && ln -sf /etc/machine-id /var/lib/dbus/machine-id
+	/usr/bin/dbus-uuidgen --ensure=/etc/machine-id
+
+	# We need to test if /var/run/dbus exists, since script will fail if it does not
+	checkpath -q -d /var/run/dbus 
+}
+
+stop_post() {
+	[ ! -S "${dbus_socket}" ] || rm -f "${dbus_socket}"
 }
 
 reload() {
-  ebegin "Reloading system message bus configuration..."
-  if [ -e "$pidfile" ]; then
-    pid=$(cat $pidfile)
-    kill -HUP $pid
-  else
-    killall -HUP dbus-daemon
-  fi
-  eend $?
+	ebegin "Reloading D-BUS messagebus config"
+	/usr/bin/dbus-send --print-reply --system --type=method_call \
+			--dest=org.freedesktop.DBus \
+			/ org.freedesktop.DBus.ReloadConfig > /dev/null
+	eend $?
 }
 
