Fix and reorganize wlsbuild: * a52dec: Updated SlackBuild. * alsa-plugins: Updated SlackBuild. * appmenu-gtk: Removed. * aria2: Removed. * bogofilter: Updated SlackBuild. * bzr: Removed. * cabextract: Updated SlackBuild. * celestia: Upgraded to 1.6.1. * claws-mail: Updated SlackBuild. * claws-mail-extra-plugins: Updated SlackBuild. * clementine: Updated SlackBuild. * dvdauthor: Updated SlackBuild. * dvdstyler: Updated SlackBuild. * faac: Updated SlackBuild. * faad2: Updated SlackBuild. * ffmeg: Updated SlackBuild. * gdl: Moved to gnome. * geany: Updated SlackBuild. * gparted: Updated SlackBuild. * gst-ffmpeg: Updated SlackBuild. * gst-plugins-bad: Updated SlackBuild. * gst-plugins-base: Removed. * gst-plugins-good: Updated SlackBuild. * gst-plugins-ugly: Updated SlackBuild. * gstreamer: Removed. * gtkhtml: Moved to gnome. * gwget: Updated SlackBuild. * ifuse: Updated SlackBuild. * lame: Updated SlackBuild. * libburn: Upgraded to 1.3.0.pl01. * libisoburn: Upgraded to 1.3.0. * libisofs: Upgraded to 1.3.0. * opal: Moved to gnome. * ptlib: Moved to gnome. * speex: Updated SlackBuild. * usbmuxd: Updated SlackBuild. Add usbmuxd detection script. * wxsvg: Updated SlackBuild. * wxWidgets: Updated SlackBuild. * xvidcore: Updated SlackBuild.

diff --git a/usbmuxd/usbmuxd.SlackBuild b/usbmuxd/usbmuxd.SlackBuild
--- a/usbmuxd/usbmuxd.SlackBuild
+++ b/usbmuxd/usbmuxd.SlackBuild
@@ -59,6 +59,15 @@ fi
 
 set -e
 
+# Exit process if there is another usbmuxd installed
+EXISTS=$(pkg-config --exists libusbmuxd)
+if [ "${EXISTS}" = "" ]; then
+  echo "+===========================================================+"
+  echo "+ ERROR: Another $PRGNAM installed. Please remove it first! +"
+  echo "+===========================================================+"
+  exit 1
+fi
+
 # Setup user and group for nm-openconnect
 bailout() {
   printf "Please create user usbmux:
@@ -110,7 +119,7 @@ cat $CWD/slack-desc > $PKG/install/slack-desc
 cat $CWD/slack-required > $PKG/install/slack-required
 
 cd $PKG
-/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
+/sbin/makepkg -p -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
 
 echo "Cleaning up build directory"
 cd $WRK; rm -rf $PRGNAM-$VERSION $PKG
