Removing some unused directory and files. Removing GPG key generation line from the SlackBuild. Make it more general.

diff --git a/gtk-equinox-engine/gtk-equinox-engine.SlackBuild b/gtk-equinox-engine/gtk-equinox-engine.SlackBuild
--- a/gtk-equinox-engine/gtk-equinox-engine.SlackBuild
+++ b/gtk-equinox-engine/gtk-equinox-engine.SlackBuild
@@ -91,33 +91,33 @@ make $NUMJOBS
 make install DESTDIR=$PKG
 
 # Install a default set of themes in the right directory.
-if [ -r $CWD/equinox-themes-${VERSION}.tar.gz ]; then
-    mkdir -p $PKG/usr/share/themes
-    ( cd $PKG/usr/share/themes ;
-      echo "Installing Equinox Themes" ;
-      tar -xvf $CWD/equinox-themes-${VERSION}.tar.gz ;
-      chown -R root:root . ;
-      find . -type d -exec chmod 755 {} \;;
-      find . -type f -exec chmod 644 {} \;;
-    )
-else
-    # Warn users that the package may not work as expected
-    echo
-    echo "A usable theme tarball does not appear to exist in "
-    echo "$CWD"
-    echo "See the README for more information on where to download"
-    echo "this. (or you didn't edit the script to reflect it or "
-    echo "something else is broken)."
-    echo
-    echo "The script will continue to build a package, but some manual"
-    echo "setup may be required ager installation."
-    echo
-    echo "Type 'exit' to quit or any other key to continue the script."
-    read _continue
-    if [ "$_continue" = "exit" ]; then
-        exit 1
-    fi
-fi
+#if [ -r $CWD/equinox-themes-${VERSION}.tar.gz ]; then
+#    mkdir -p $PKG/usr/share/themes
+#    ( cd $PKG/usr/share/themes ;
+#      echo "Installing Equinox Themes" ;
+#      tar -xvf $CWD/equinox-themes-${VERSION}.tar.gz ;
+#      chown -R root:root . ;
+#      find . -type d -exec chmod 755 {} \;;
+#      find . -type f -exec chmod 644 {} \;;
+#    )
+#else
+#    # Warn users that the package may not work as expected
+#    echo
+#    echo "A usable theme tarball does not appear to exist in "
+#    echo "$CWD"
+#    echo "See the README for more information on where to download"
+#    echo "this. (or you didn't edit the script to reflect it or "
+#    echo "something else is broken)."
+#    echo
+#    echo "The script will continue to build a package, but some manual"
+#    echo "setup may be required ager installation."
+#    echo
+#    echo "Type 'exit' to quit or any other key to continue the script."
+#    read _continue
+#    if [ "$_continue" = "exit" ]; then
+#        exit 1
+#    fi
+#fi
 
 find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
   | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
