Bunch of updates to get gnome 3.8 working on my Slackware-current. * alsa-plugins: Updated SlackBuild. * aqemu: Updated SlackBuild. * atkmm: Upgraded to 2.22.6. * cairomm: Updated SlackBuild. * farstream: Upgraded to 0.2.3. * gc: Updated SlackBuild. * geany: Upgraded to 1.23.1. * geoclue: Updated SlackBuild. * glibmm: Upgraded to 2.36.2. * gst-libav: Added version 1.0.7. Need gstreamer-1. * gst-plugins-bad-1: Added version 1.0.7. Need gstreamer-1. * gst-plugins-base-1: Added version 1.0.7. Need gstreamer-1. * gst-plugins-good-1: Added version 1.0.7. Need gstreamer-1. * gst-plugins-ugly-1: Added version 1.0.7. Need gstreamer-1. * gstreamer-1: Added version 1.0.7. Needed by gnome 3.8. * gtkmm3: Upgraded to 3.8.1. * heimdal-libraries: Removed. * heimdal: Added to make heimdal and heimdal-libraries at once. * itstool: Removed. Already provided by Slackware. * json-c: Upgraded to 0.11. * json-glib: Moved to gnome. * libnice: Upgraded to 0.1.4. * libpst: Moved to gnome. * libunique-1: Added version 1.1.6. * libunique: Moved to gnome. * libvpx: Updated SlackBuild. * libwebp: Added version 0.3.1. Needed by webkitgtk 2.x. * libxml++: Updated SlackBuild. * liferea: Moved to gnome. * pangomm: Upgraded to 2.34.0. * pulseaudio: Upgraded to 4.0. * pygi: Removed. * pylint: Moved to gnome. * python-isodate: Moved to gnome. * python-logilab-astng: Moved to gnome. * python-logilab-common: Moved to gnome. * python-rdflib: Moved to gnome. * qemu: Upgraded to 1.5.0. * setuptools: Updated SlackBuild. * telepathy-farstream: Upgraded to 0.6.0. * telepathy-gabble: Upgraded to 0.17.5. * telepathy-glib: Upgraded to 0.21.1. * telepathy-logger: Upgraded to 0.8.0. * telepathy-mission-control: Upgraded to 5.15.0. * vte: Removed. * webkitgtk: Upgraded to 1.10.2. * webkitgtk2: Added version 2.0.3. Needed by gnome 3.8. * xapian-core: Moved to gnome.

diff --git a/webkitgtk/webkitgtk.SlackBuild b/webkitgtk/webkitgtk.SlackBuild
--- a/webkitgtk/webkitgtk.SlackBuild
+++ b/webkitgtk/webkitgtk.SlackBuild
@@ -2,7 +2,7 @@
 
 # Slackware build script for webkitgtk
 
-# Copyright 2010-2012  Widya Walesa <walecha99@gmail.com>
+# Copyright 2010-2013  Widya Walesa <walecha99@gmail.com>
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -24,14 +24,13 @@
 # YOUR DATA IS DESTROYED, YOUR HOUSE BURNS DOWN OR YOUR DOG RUNS OFF.
 
 PRGNAM=webkitgtk
-VERSION=1.8.3
+VERSION=1.10.2
 BUILD=1
 TAG=${TAG:-_wls}
-NUMJOBS=${NUMJOBS:--j3}
+NUMJOBS=${NUMJOBS:--j1}
 
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
-    i?86) ARCH=i486 ;;
     arm*) ARCH=arm ;;
        *) ARCH=$( uname -m ) ;;
   esac
@@ -44,7 +43,11 @@ OUTPUT=${OUTPUT:-/tmp}
 DOCS="ChangeLog INSTALL NEWS README"
 
 if [ "$ARCH" = "i486" ]; then
-  SLKCFLAGS="-O2 -pipe -march=i486 -mtune=i686"
+  echo "ERROR: $ARCH is not supported!"
+  echo "Minimum requirement is i586 CPU(s)!"
+  exit 1
+elif [ "$ARCH" = "i586" ]; then
+  SLKCFLAGS="-O2 -pipe -march=i586 -mtune=i686"
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "i686" ]; then
   SLKCFLAGS="-O2 -pipe -march=i686 -mtune=i686"
@@ -62,9 +65,14 @@ set -e
 rm -rf $PKG
 mkdir -p $WRK $PKG $OUTPUT
 cd $WRK
-rm -rf webkit-$VERSION
-tar xvf $CWD/webkit-$VERSION.tar.?z*
-cd webkit-$VERSION
+rm -rf $PRGNAM-$VERSION
+tar xvf $CWD/$PRGNAM-$VERSION.tar.?z*
+cd $PRGNAM-$VERSION
+
+# Fix librt linking using patch from LFS
+# https://bugs.webkit.org/show_bug.cgi?id=103194
+cat $CWD/webkitgtk-1.10.2-fix_librt_linking-1.patch | patch -p1
+
 chown -R root:root .
 find . \
  \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
@@ -75,7 +83,6 @@ find . \
 CFLAGS="$SLKCFLAGS" \
 CXXFLAGS="$SLKCFLAGS" \
 ./configure \
-  --build=$ARCH-slackware-linux --host=$ARCH-slackware-linux \
   --program-prefix= --program-suffix= \
   --prefix=/usr --exec-prefix=/usr \
   --bindir=/usr/bin --sbindir=/usr/sbin \
@@ -85,13 +92,12 @@ CXXFLAGS="$SLKCFLAGS" \
   --localstatedir=/var --sharedstatedir=/var/lib \
   --disable-static --enable-shared \
   --enable-introspection=yes \
-  --with-unicode-backend=icu \
   --enable-webgl \
   --enable-jit \
   --enable-geolocation \
   --enable-webkit2 \
 
-make
+make V=1 $NUMJOBS
 make install DESTDIR=$PKG
 
 find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
@@ -110,4 +116,4 @@ cd $PKG
 /sbin/makepkg -p -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
 
 echo "Cleaning up build directory"
-cd $WRK; rm -rf webkit-$VERSION $PKG
+cd $WRK; rm -rf $PRGNAM-$VERSION $PKG
