Upgrade several package after slackware{64} current sync.

diff --git a/wine/wine.SlackBuild b/wine/wine.SlackBuild
--- a/wine/wine.SlackBuild
+++ b/wine/wine.SlackBuild
@@ -24,11 +24,11 @@
 # YOUR DATA IS DESTROYED, YOUR HOUSE BURNS DOWN OR YOUR DOG RUNS OFF.
 
 PRGNAM=wine
-VERSION=${VERSION:-1.7.48}
-BUILD=${BUILD:-1}
+VERSION=${VERSION:-1.7.49}
+BUILD=${BUILD:-2}
 TAG=${TAG:-_wls}
 NUMJOBS=${NUMJOBS:--j7}
-STAGING=${STAGING:-1}
+STAGING=${STAGING:-0}
 D3D9=${D3D9:-0}
 
 if [ -z "$ARCH" ]; then
@@ -45,8 +45,8 @@ PKG=$WRK/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
 DOCS="ANNOUNCE AUTHORS COPYING.LIB LICENSE* README VERSION"
 
-if [ "$ARCH" = "i486" ]; then
-  SLKCFLAGS="-O2 -pipe -march=i486 -mtune=i686"
+if [ "$ARCH" = "i586" ]; then
+  SLKCFLAGS="-O2 -pipe -march=i586 -mtune=i686"
   SLKLDFLAGS="-L/usr/lib -ldl"
   LIBDIRSUFFIX=""
   ENABLE_64=""
@@ -73,12 +73,42 @@ cd $WRK
 rm -rf $PRGNAM*
 echo "extracting $PRGNAM-$VERSION"
 tar xf $CWD/$PRGNAM-$VERSION.tar.?z*
+cd $PRGNAM-$VERSION
 
 if [ "$STAGING" = "1" ]; then
-  echo "extracting $PRGNAM-staging-$VERSION"
-  tar xf $CWD/$PRGNAM-staging-$VERSION.tar.?z*
+  if [ -f $CWD/$PRGNAM-staging-$VERSION.tar.?z* ]; then
+    echo "BUILDING WINE STAGING: $VERSION"
+    sleep 5
+    tar -C $WRK -xf $CWD/$PRGNAM-staging-$VERSION.tar.?z*
+    mv ../$PRGNAM-staging-$VERSION/* .
+    make -C patches DESTDIR=$WRK/$PRGNAM-$VERSION install || exit 1
+    sed -i -e 's!^loader server: libs/port libs/wine tools.*!& include!' Makefile.in
+  else
+    echo "BUILDING WINE STAGING: FAILED! $PRGNAM-staging-$VERSION not found!"
+    exit 1
+  fi
+else
+  echo "BUILDING WINE STAGING: FALSE"
+  sleep 5
 fi
-cd $PRGNAM-$VERSION
+
+cat $CWD/wine-cjk.patch | patch -p1 || exit 1
+
+if [ "$D3D9" = "1" ]; then
+  if [ -f $CWD/wine-d3d9-$VERSION.patch ]; then
+    echo "BUILDING WINE D3D9: $VERSION"
+    sleep 5
+    cat $CWD/wine-d3d9-$VERSION.patch | patch -p1 || exit 1
+    ENABLE_NINE="--with-d3dadapter"
+  else
+    echo "BUILDING WINE D3D9: FAILED! $PRGNAM-d3d9-$VERSION.patch not found!"
+    exit 1
+  fi
+else
+  echo "BUILDING WINE D3D9: FALSE"
+  sleep 5
+fi
+
 chown -R root:root .
 find . \
  \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
@@ -86,21 +116,7 @@ find . \
  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
  -exec chmod 644 {} \;
 
-if [ "$STAGING" = "1" ]; then
-  mv ../$PRGNAM-staging-$VERSION/* .
-  make -C patches DESTDIR=$WRK/$PRGNAM-$VERSION install
-  sed -i -e 's!^loader server: libs/port libs/wine tools.*!& include!' Makefile.in
-fi
-
-if [ "$D3D9" = "1" ]; then
-  echo "Building wine d3d9"
-  cat $CWD/wine-d3d9-$VERSION.patch | patch -p1
-  ENABLE_NINE="--with-d3dadapter"
-fi
-
-cat $CWD/wine-cjk.patch | patch -p1 || exit 1
-
-autoreconf -ivsf
+autoreconf -fi
 
 echo "Creating build directory $WRK/$PRGNAM"
 rm -rf $WRK/$PRGNAM
@@ -124,13 +140,12 @@ CXXFLAGS="$SLKCFLAGS -DHAVE_ATTR_XATTR_H=1" \
   --with-x \
   --with-opengl \
   --with-xattr \
-  --without-gstreamer \
   ${ENABLE_NINE} \
   ${ENABLE_64} \
   || exit 1
 
 make depend || exit 1
-make || exit 1
+make $NUMJOBS || make || exit 1
 make install DESTDIR=$PKG || exit 1
 
 if [ "$ARCH" = "x86_64" ]; then
@@ -160,12 +175,11 @@ if [ "$ARCH" = "x86_64" ]; then
     --with-x \
     --with-opengl \
     --with-xattr \
-    --without-gstreamer \
     ${ENABLE_NINE} \
     || exit 1
 
   make depend || exit 1
-  make CFLAGS+="-march=native -pipe -mstackrealign -mincoming-stack-boundary=2" CXXFLAGS+="-mstackrealign -mincoming-stack-boundary=2" || exit 1
+  make $NUMJOBS || make || exit 1
   make install DESTDIR=$PKG || exit 1
   unset PKG_CONFIG_PATH
 fi
