UPDATES 201601020806
* opencl-headers: Upgraded to specification 2.1.
* radeon-profile: Upgraded.
* wine: Upgraded to 1.9.0.

diff --git a/wine/wine.SlackBuild b/wine/wine.SlackBuild
--- a/wine/wine.SlackBuild
+++ b/wine/wine.SlackBuild
@@ -24,8 +24,8 @@
 # YOUR DATA IS DESTROYED, YOUR HOUSE BURNS DOWN OR YOUR DOG RUNS OFF.
 
 PRGNAM=wine
-VERSION=${VERSION:-1.8}
-SRCVERSION=${SRCVERSION:-1.8}
+VERSION=${VERSION:-1.9.0}
+SRCVERSION=${SRCVERSION:-1.9.0}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_wls}
 NUMJOBS=${NUMJOBS:--j7}
@@ -57,7 +57,7 @@ elif [ "$ARCH" = "i686" ]; then
   LIBDIRSUFFIX=""
   ENABLE_64=""
 elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2 -pipe -fPIC"
+  SLKCFLAGS="-O2 -pipe -fPIC -mtune=generic"
   SLKLDFLAGS="-L/usr/lib64 -ldl -lm -lpthread"
   LIBDIRSUFFIX="64"
   ENABLE_64="--enable-win64"
@@ -95,25 +95,25 @@ fi
 
 cat $CWD/wine-cjk.patch | patch -p1 || exit 1
 
-if [ "$D3D9" = "yes" ]; then
-  if [ -f $CWD/wine-d3d9-$VERSION.patch ]; then
-    echo "BUILDING WINE D3D9: $VERSION"
-    sleep 5
-    cat $CWD/wine-d3d9-$VERSION.patch | patch -p1 || exit 1
-    ENABLE_NINE="--with-d3dadapter=yes --with-d3dadapter-dri2-fallback=yes"
-  elif [ ! -f $CWD/wine-d3d9-$VERSION.patch ] && [ -f $CWD/wine-d3d9-latest.patch ]; then
-      echo "BUILDING WINE D3D9: Using latest git patch"
-      sleep 5
-      zcat $CWD/wine-d3d9-latest.patch.gz | patch -p1 || exit 1
-      ENABLE_NINE="--with-d3dadapter=yes --with-d3dadapter-dri2-fallback=yes"
-  elif [ ! -f $CWD/wine-d3d9-$VERSION.patch ] && [ ! -f $CWD/wine-d3d9-latest.patch.gz ]; then
-    echo "BUILDING WINE D3D9: FAILED! $PRGNAM-d3d9-$VERSION.patch not found!"
-    exit 1
-  fi
-else
-  echo "BUILDING WINE D3D9: FALSE"
-  sleep 5
-fi
+# if [ "$D3D9" = "yes" ]; then
+#   if [ -f $CWD/wine-d3d9-$VERSION.patch ]; then
+#     echo "BUILDING WINE D3D9: $VERSION"
+#     sleep 5
+#     cat $CWD/wine-d3d9-$VERSION.patch | patch -p1 || exit 1
+#     ENABLE_NINE="--with-d3dadapter=yes --with-d3dadapter-dri2-fallback=yes"
+#   elif [ ! -f $CWD/wine-d3d9-$VERSION.patch ] && [ -f $CWD/wine-d3d9-latest.patch ]; then
+#       echo "BUILDING WINE D3D9: Using latest git patch"
+#       sleep 5
+#       zcat $CWD/wine-d3d9-latest.patch.gz | patch -p1 || exit 1
+#       ENABLE_NINE="--with-d3dadapter=yes --with-d3dadapter-dri2-fallback=yes"
+#   elif [ ! -f $CWD/wine-d3d9-$VERSION.patch ] && [ ! -f $CWD/wine-d3d9-latest.patch.gz ]; then
+#     echo "BUILDING WINE D3D9: FAILED! $PRGNAM-d3d9-$VERSION.patch not found!"
+#     exit 1
+#   fi
+# else
+#   echo "BUILDING WINE D3D9: FALSE"
+#   sleep 5
+# fi
 
 chown -R root:root .
 find . \
@@ -128,10 +128,7 @@ echo "Creating build directory $WRK/$PRGNAM"
 rm -rf $WRK/$PRGNAM
 mkdir -p $WRK/$PRGNAM
 cd $WRK/$PRGNAM
-LDFLAGS="$SLKLDFLAGS" \
-CPPFLAGS="${CPPFLAGS/-D_FORTIFY_SOURCE=2/} -D_FORTIFY_SOURCE=0" \
-CFLAGS="$SLKCFLAGS -DHAVE_ATTR_XATTR_H=1" \
-CXXFLAGS="$SLKCFLAGS -DHAVE_ATTR_XATTR_H=1" \
+
 ../$PRGNAM-$SRCVERSION/configure \
   --program-prefix= --program-suffix= \
   --prefix=/usr --exec-prefix=/usr \
@@ -151,23 +148,20 @@ CXXFLAGS="$SLKCFLAGS -DHAVE_ATTR_XATTR_H=1" \
   ${ENABLE_64} \
   || exit 1
 
-make depend || exit 1
+# make depend || exit 1
 make $NUMJOBS || make || exit 1
 
 if [ "$ARCH" = "x86_64" ]; then
   echo "Building WINE 32-bit compat for $ARCH"
   rm -rf $WRK/$PRGNAM-wow64
   mkdir -p $WRK/$PRGNAM-wow64
-   cd $WRK/$PRGNAM-wow64
+  cd $WRK/$PRGNAM-wow64
 
   # Set 32-bit pkgconfig path as needed by gstreamer
   unset PKG_CONFIG_PATH
   export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig"
 
-  CPPFLAGS="${CPPFLAGS/-D_FORTIFY_SOURCE=2/} -D_FORTIFY_SOURCE=0" \
-  CFLAGS="$SLKCFLAGS -DHAVE_ATTR_XATTR_H=1" \
-  CXXFLAGS="$SLKCFLAGS -DHAVE_ATTR_XATTR_H=1" \
-  ../$PRGNAM-$SRCVERSION/configure \
+../$PRGNAM-$SRCVERSION/configure \
     --with-wine64=../${PRGNAM} \
     --program-prefix= --program-suffix= \
     --prefix=/usr --exec-prefix=/usr \
@@ -187,7 +181,9 @@ if [ "$ARCH" = "x86_64" ]; then
     || exit 1
 
   make depend || exit 1
-  make $NUMJOBS || make || exit 1
+  make CFLAGS+="-march=native -pipe -mstackrealign -mincoming-stack-boundary=2" \
+       CXXFLAGS+="-mstackrealign -mincoming-stack-boundary=2" \
+       $NUMJOBS || make || exit 1
   make install DESTDIR=$PKG || exit 1
   unset PKG_CONFIG_PATH
 fi
